### ISSUE TITLE
Error: A required privilege is not held by the client

### ISSUE THREAD

**Issue by chuacw** [NoMoreFood/Repacls#2]
Run the following as an Administrator:

repacls.exe /Path C:\ /InheritChildren

Encountered these errors:
FILE: C:\
  ERROR: Unable to read file security
  ERROR DETAIL: A required privilege is not held by the client.
FILE: C:\.rnd
  ERROR: Unable to read file security
  ERROR DETAIL: A required privilege is not held by the client.
FILE: C:\$RECYCLE.BIN
  ERROR: Unable to read file security
  ERROR DETAIL: A required privilege is not held by the client.

Would you add code to impersonate the SYSTEM user, so that these privilege issues would not be encountered?

**Comment by NoMoreFood** [comment]
Sorry for the very late response.  You can always use psexec -s -i cmd.exe to launch this as system.  Alternatively, make sure the current user just has the local security policy to backup and restore files (usually is granted to Administrators).  Not interested in adding code to impersonate system.
